Fix missing data, add fuzzy matching and pass/fail of VisIt's test suite to Azure CI (#20005)

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -20,11 +20,17 @@ variables:
     ../../src/test/tests/databases/blueprint.py
     ../../src/test/tests/databases/blueprint_export.py
     ../../src/test/tests/hybrid/ddf.py
-    ../../src/test/tests/unit/assert_simple.py
     ../../src/test/tests/unit/default_methods.py
     ../../src/test/tests/unit/convert2to3.py
     ../../src/test/tests/unit/atts_assign.py
     ../../src/test/tests/unit/test_value_simple.py
+    ../../src/test/tests/unit/annotation_objects.py
+    ../../src/test/tests/unit/protocol.py
+    ../../src/test/tests/unit/utility.py
+    ../../src/test/tests/expressions/ghost_zoneid_expr.py
+    ../../src/test/tests/expressions/global_stats.py
+    ../../src/test/tests/expressions/math_expr.py
+    ../../src/test/tests/expressions/tensor_expr.py
 
 # only build merge target pr to develop
 trigger: none
@@ -36,6 +42,7 @@ pr:
     - '[0-9].[0-9][0-9]RC'
   paths:
     include:
+    - 'azure-pipelines.yml'
     - '**/CMakeLists.txt'
     - '**/*.cmake'
     - '**/*.in'
@@ -47,11 +54,17 @@ pr:
     - 'src/test/tests/databases/blueprint.py'
     - 'src/test/tests/databases/blueprint_export.py'
     - 'src/test/tests/hybrid/ddf.py'
-    - 'src/test/tests/unit/assert_simple.py'
     - 'src/test/tests/unit/default_methods.py'
     - 'src/test/tests/unit/convert2to3.py'
     - 'src/test/tests/unit/atts_assign.py'
     - 'src/test/tests/unit/test_value_simple.py'
+    - 'src/test/tests/unit/annotation_objects.py'
+    - 'src/test/tests/unit/protocol.py'
+    - 'src/test/tests/unit/utility.py'
+    - 'src/test/tests/expressions/ghost_zoneid_expr.py'
+    - 'src/test/tests/expressions/global_stats.py'
+    - 'src/test/tests/expressions/math_expr.py'
+    - 'src/test/tests/expressions/tensor_expr.py'
 
 # fast fail consistency checks
 stages:
@@ -118,46 +131,15 @@ stages:
            # fetch subset of test data (silo + blueprint)
            #################################
            cd data
-           git lfs pull --include silo_amr_test_data.tar.xz
-           git lfs pull --include silo_ghost_test_data.tar.xz
-           git lfs pull --include silo_hdf5_test_data.tar.xz
-           git lfs pull --include silo_pdb_test_data.tar.xz
-           git lfs pull --include silo_sph_test_data.tar.xz
-           git lfs pull --include blueprint_v0.3.1_test_data.tar.xz
-           git lfs pull --include blueprint_v0.3.1_mfem_test_data.tar.xz
-           git lfs pull --include blueprint_v0.7.0_venn_test_data.tar.xz
-           git lfs pull --include blueprint_v0.8.2_braid_examples_test_data.tar.xz
-           git lfs pull --include blueprint_v0.8.2_polytess_test_data.tar.xz
-           git lfs pull --include blueprint_v0.8.3_devilray_mfem_test_data
-           git lfs pull --include blueprint_v0.8.4_part_map_examples.tar.xz
-           git lfs pull --include blueprint_v0.8.4_strided_structured_examples.tar.xz
-           git lfs pull --include blueprint_v0.8.4_strided_structured_examples.tar.xz
-           git lfs pull --include blueprint_v0.8.6_rz_examples.tar.xz
-           git lfs pull --include blueprint_v0.8.6_1d_curve_examples.tar.xz
-           git lfs pull --include blueprint_v0.8.7_venn_modded_matnos_example.tar.xz
-           git lfs pull --include blueprint_v0.8.7_polytopal_mesh_no_offsets.tar.xz
+           git lfs pull --include "**/silo*.tar.xz"
+           git lfs pull --include "**/blueprint*.tar.xz"
            cd ../
            git lfs pull  --include test/baseline/databases/silo
            git lfs pull  --include test/baseline/databases/blueprint
+           git lfs pull  --include test/baseline/databases/blueprint_export
+           git lfs pull  --include test/baseline/hybrid/ddf
            cd build/testdata/
-           tar xvf ../../data/silo_amr_test_data.tar.xz
-           tar xvf ../../data/silo_ghost_test_data.tar.xz
-           tar xvf ../../data/silo_hdf5_test_data.tar.xz
-           tar xvf ../../data/silo_pdb_test_data.tar.xz
-           tar xvf ../../data/silo_sph_test_data.tar.xz
-           tar xvf ../../data/blueprint_v0.3.1_test_data.tar.xz
-           tar xvf ../../data/blueprint_v0.3.1_mfem_test_data.tar.xz
-           tar xvf ../../data/blueprint_v0.7.0_venn_test_data.tar.xz
-           tar xvf ../../data/blueprint_v0.8.2_braid_examples_test_data.tar.xz
-           tar xvf ../../data/blueprint_v0.8.2_polytess_test_data.tar.xz
-           tar xvf ../../data/blueprint_v0.8.3_devilray_mfem_test_data
-           tar xvf ../../data/blueprint_v0.8.4_part_map_examples.tar.xz
-           tar xvf ../../data/blueprint_v0.8.4_strided_structured_examples.tar.xz
-           tar xvf ../../data/blueprint_v0.8.4_strided_structured_examples.tar.xz
-           tar xvf ../../data/blueprint_v0.8.6_rz_examples.tar.xz
-           tar xvf ../../data/blueprint_v0.8.6_1d_curve_examples.tar.xz
-           tar xvf ../../data/blueprint_v0.8.7_venn_modded_matnos_example.tar.xz
-           tar xvf ../../data/blueprint_v0.8.7_polytopal_mesh_no_offsets.tar.xz
+           for f in ../../data/silo*.tar.xz ../../data/blueprint*.tar.xz; do tar xvf "$f"; done
         displayName: 'Prep Test Data'
 
       - script: |
@@ -173,15 +155,21 @@ stages:
            # add to ld_lib path (rpaths are missing?)
            export LD_LIBRARY_PATH=${VTK_LIB_DIR}:${OSPRAY_LIB_DIR}:${QT_LIB_DIR}
            # run test suite on silo + blueprint tests
-           export TESTS=$(python_test_files)
-           ./run_visit_test_suite.sh  -v ${TESTS}
+           export TESTS="$(python_test_files)"
+           ./run_visit_test_suite.sh --fuzzy --pixdiff 10 --avgdiff 10 --numdiff 0.1 -v ${TESTS}
+           hasFailed="$(grep Failed\\\|Unacceptable\\\|OS-Killed output/html/index.html)"
+           if [[ -n "$hasFailed" ]]; then
+             exit 1 # tests failed
+           else
+             exit 0 # tests passed
+           fi
         displayName: 'Run Tests'
 
       - task: CopyFiles@2
         inputs:
           contents: 'build/test/output/html/**'
           targetFolder: $(Build.ArtifactStagingDirectory)
-        condition: always()
+        condition: succeededOrFailed()
 
       - script: |
            #################################
@@ -196,13 +184,13 @@ stages:
         inputs:
           contents: 'build/resources/help/en_US/manual/**'
           targetFolder: $(Build.ArtifactStagingDirectory)
-        condition: always()
+        condition: succeededOrFailed()
 
       - task: PublishBuildArtifacts@1
         inputs:
           pathToPublish: $(Build.ArtifactStagingDirectory)
           artifactName: VisIt_Test_Outputs
-        condition: always()
+        condition: succeededOrFailed()
 
       # - script: |
       #      #################################
